knp_paginator:
  page_range: 5       # nombre de pages à afficher dans la pagination
  default_options:
    page_name: page  # nom du paramètre de requête pour la page
    sort_field_name: sort
    sort_direction_name: direction
    distinct: true
  template:
    pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
